We want to verify that our Singular Value Decomposition of a matrix A is correct and that $U$, $V$ and $\Sigma$ are indeed matrices satisfying the properties of the SVD.

In [15]:
import numpy as np
import numpy.linalg as LA

def svdVerifier(A, U, V, Sigma):
    print( np.matmul(U, np.matmul(Sigma, V)) )
    print( np.matmul(U, np.transpose(U)) )
    print( np.matmul(V, np.transpose(V)))
    print( Sigma )

A = np.array([[2, 0 , -1], [0, 1, 0], [-1, 0, 2]])

U = np.array([[1/2, 1/(np.sqrt(2)), 1/2], [1/(np.sqrt(2)), 0, -1/(np.sqrt(2))], [1/2, -1/(np.sqrt(2)), 1/2]])

Sigma = np.array([[1, 0, 0], [0, 3, 0], [0, 0, 1]])

print(A)
print(U)
print(Sigma)

svdVerifier(A, U, U, Sigma)

[[ 2  0 -1]
 [ 0  1  0]
 [-1  0  2]]
[[ 0.5         0.70710678  0.5       ]
 [ 0.70710678  0.         -0.70710678]
 [ 0.5        -0.70710678  0.5       ]]
[[1 0 0]
 [0 3 0]
 [0 0 1]]
[[ 2.  0. -1.]
 [ 0.  1.  0.]
 [-1.  0.  2.]]
[[1.00000000e+00 0.00000000e+00 8.32667268e-17]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [8.32667268e-17 0.00000000e+00 1.00000000e+00]]
[[1.00000000e+00 0.00000000e+00 8.32667268e-17]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [8.32667268e-17 0.00000000e+00 1.00000000e+00]]
[[1 0 0]
 [0 3 0]
 [0 0 1]]


We see that our SVD is correct; $U\Sigma V^T = A$, $UU^T=I$, $VV^T=I$, and $\Sigma$ is the matrix with the singular  values of $AA^T$ on its diagonal.